local ChangeLog = {}

ChangeLog.Entries = {
	{
		Date = "September 30th, 2026",
		Title = "Initial Release to QA Team",
		Items = {
			{ Type = "Added", Text = "Welcome to USARF." },
			{ Type = "Added", Text = "New centralized main menu interface." },
			{ Type = "Added", Text = "Improved radio communications UI." },
			{ Type = "Added", Text = "AFK Detection integrated with paycheck system." },
			{ Type = "Added", Text = "Introduced anti exploit system." },
			{ Type = "Added", Text = "Handcuffs system." },
			{ Type = "Added", Text = "Escorting support." },
			{ Type = "Added", Text = "Authorization integration between Cmdr and clipboard (tool)." },
			{ Type = "Added", Text = "Leaving while cuffed gives a game warning." },
			{ Type = "Added", Text = "Test Subject Clans." },
			{ Type = "Modified", Text = "Improved the cloak and scrambler system for intel departments." },
			{ Type = "Modified", Text = "Riot system now bought via Gold currency or Robux - lasts 10 minutes." },
			{ Type = "Added", Text = "Medal ribbons to players' uniform." },
			{ Type = "Added", Text = "Location tracker on VIPs for Secret Service." },
			{ Type = "Modified", Text = "Facility announcement and status redesigned" },
			{ Type = "Added", Text = "Classified - VPOTUS+ info" },
			{ Type = "Modified", Text = "Gun system reworked and improved." },
			{ Type = "Added", Text = "Added in ammo crates, two medical kits, and more. . ." },
		},
	},
}

return ChangeLog
