local LoadoutConfig = {}

LoadoutConfig.Teams = {

	["Test Subject"] = {
		Default = {},
	},

	["Private Military Company"] = {
		Default = {
			"AK-47",
		},
	},

	["Facility Personnel"] = {
		Default = {
			"",
		},
	},

	["Engineering & Technical"] = {
		Default = {
			"Wrench",
		},
	},

	["Medical"] = {
		Default = {
			"Medkit",
		},
	},

	["Research"] = {
		Default = {
			"Authorization Clipboard",
		},
	},

	["Rules & Regulations"] = {
		Default = {
			"",
		},
	},

	["108th Infantry"] = {
		Default = {
			"M4A1",
			"Glock 18",
			"Handcuffs",
			"Ammo Box",
		},
	},

	["137th MP"] = {
		Default = {
			"M4A1",
			"Glock 18",
			"Handcuffs",
			"Ammo Box",
		},
	},

	["1st Spec Ops A.I.G"] = {
		Default = {
			"AR15",
			"Glock 18",
			"Handcuffs",
			"Ammo Box",
			"Riot Shield",
		},
	},

	["CIA"] = {
		Default = {
			"Kriss Vector",
			"Glock 18",
			"Handcuffs",
			"Ammo Box",
		},
	},

	["FBI"] = {
		Default = {
			"SCAR-H",
			"Glock 18",
			"Handcuffs",
			"Ammo Box",
		},
	},

	["FDS"] = {
		Default = {
			"G36C",
			"Glock 18",
			"Handcuffs",
			"Ammo Box",
		},
	},

	["Secret Service"] = {
		Default = {
			"M27 IAR",
			"Remington 870",
			"Glock 18",
			"Handcuffs",
			"Ammo Box",
		},
	},

	["USAF"] = {
		Default = {
			"M4A1",
			"Glock 18",
			"Ammo Box",
		},
	},

	["DoD"] = {
		Default = {
			"M4A1",
			"Glock 18",
			"Ammo Box",
		},
	},
}

LoadoutConfig.Gamepasses = {
	Minigun = "Minigun",
	BoomBox = "BoomBox",
	MP5 = "MP5",
	["Glock-17"] = "P226",
}

return LoadoutConfig
