local LoadoutConfig = {}

LoadoutConfig.Teams = {

	["Test Subject"] = {
		Default = {},
	},

	["Private Military Company"] = {
		Default = {
			"Radio",
			"MP5",
		},
	},

	["Facility Personnel"] = {
		Default = {
			"Radio",
			"Flashlight",
		},
	},

	["Engineering & Technical"] = {
		Default = {
			"Radio",
			"Flashlight",
		},
	},

	["Medical"] = {
		Default = {
			"Radio",
			"Medkit",
		},
	},

	["Research"] = {
		Default = {
			"Radio",
		},
	},

	["Rules & Regulations"] = {
		Default = {
			"Radio",
			"Flashlight",
		},
	},

	["108th Infantry"] = {
		Default = {
			"Radio",
			"M4A1",
		},
	},

	["137th MP"] = {
		Default = {
			"Radio",
			"Taser",
			"Handcuffs",
		},
	},

	["1st Spec Ops A.I.G"] = {
		Default = {
			"Radio",
			"M4A1",
		},
	},

	["CIA"] = {
		Default = {
			"Radio",
			"P226",
		},
	},

	["FBI"] = {
		Default = {
			"Radio",
			"P226",
		},
	},

	["FDS"] = {
		Default = {
			"Radio",
			"P226",
		},
	},

	["Secret Service"] = {
		Default = {
			"Radio",
			"P226",
		},
	},

	["USAF"] = {
		Default = {
			"Radio",
			"M4A1",
		},
	},

	["DoD"] = {
		Default = {
			"Radio",
			"P226",
		},
	},
}

LoadoutConfig.Gamepasses = {
	Minigun = "Minigun",
	BoomBox = "BoomBox",
	MP5 = "MP5",
	P226 = "P226",
}

return LoadoutConfig